# Generated by Django 6.1.1 on 2026-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service_DB',
            fields=[
                ('Reg_No', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Vehicle_no', models.CharField(max_length=7)),
                ('DoR', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
